### ISSUE TITLE
rewrite UI of pLib

### ISSUE THREAD

**Issue by skarockoi** [skarockoi/pHake#48]
- focus on extendability and low cpu/gpu usage
- take inspiration from React Class Components

**Comment by xhz8s** [comment]
hide pHake, when game is not in focus

**Comment by xhz8s** [comment]
accidental close

**Comment by xhz8s** [comment]
make us of standard template for Ui elements like pCheat()

**Comment by skarockoi** [comment]
deleting branch rn, will wait for SFML 3 I think
