### ISSUE TITLE
pHake 5.8  Some minor problems

### ISSUE THREAD

**Issue by Xsans711** [skarockoi/pHake#53]
Thank you for continuing to update and improve!
There seem to be several problems:

1. NoWanted is disabled, but the NoWanted mode is enabled by default

2. NoClip seems to overlap with the Fly function. Opening NoClip also opens Fly

That's all ,TS.

**Comment by skarockoi** [comment]
Heyy thank you for the information. I fixed NoWanted with [this commit](https://github.com/skarockoi/pHake/commit/f2f5c5232188d49c176e4d65410111519c4a2b91). And NoClip is supposed to be bundled with Fly, otherwise you wouldn't be able to move.

**Comment by Xsans711** [comment]
This is the holiday automatic reply email from QQ mailbox.Hello, I'm on vacation recently and can't reply to your email in person. I will reply to you as soon as possible at any time.
